import Image from '@/components/ImageKitImage';
import Link from 'next/link';
import { Award, Check, Globe2, Heart, ShieldCheck, Sparkles, Star } from 'lucide-react';

export const metadata = {
  title: 'About Us | Nepali Rudraksha',
  description: 'Learn about our journey of bringing authentic, lab-certified Rudraksha beads from the Himalayas of Nepal to the world.',
};

const storyImage = '/images/handpicked_for_spiritual/WhatsApp%20Image%202026-09-18%20at%205.15.52%20PM.jpeg';
const heritageImage = '/images/ancient_wisdom/WhatsApp%20Image%202026-09-18%20at%205.15.40%20PM.jpeg';

export default function About() {
  return (
    <main className="w-full overflow-hidden bg-[#fffdf8]">
      <section className="relative isolate min-h-[380px] overflow-hidden sm:min-h-[440px]">
        <Image src="/images/banner/ChatGPT%20Image%20Sep%2018%2C%202026%2C%2007_01_56%20PM.png" alt="Himalayan temple and Rudraksha" fill sizes="100vw" className="-z-10 object-cover object-center" priority />
        <div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#082d21]/88 via-[#123a2d]/58 to-[#102c22]/20" />
        <div className="mx-auto flex min-h-[380px] max-w-7xl items-center px-5 py-12 sm:min-h-[440px] sm:px-10 lg:px-12 xl:px-16">
          <div className="max-w-2xl"><p className="text-[10px] font-extrabold tracking-[0.22em] text-[#f2d18d] uppercase">Our story</p><h1 className="mt-4 font-[family-name:var(--font-display)] text-[44px] font-bold leading-[0.88] text-white sm:text-[61px]">Where divinity<br />meets authenticity</h1><p className="mt-5 max-w-xl text-[13px] leading-relaxed text-white/85 sm:text-[16px]">Born from deep reverence for Himalayan traditions, we bring genuine Rudraksha from the sacred forests of Nepal to spiritual seekers everywhere.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/shop" className="inline-flex h-11 items-center rounded-full bg-[#f1ca7f] px-6 text-[12px] font-bold text-[#17382b] transition-colors hover:bg-[#f8d998]">Explore the collection</Link><Link href="/contact" className="inline-flex h-11 items-center rounded-full border border-white/40 bg-white/10 px-6 text-[12px] font-bold text-white backdrop-blur-sm transition-colors hover:bg-white/20">Speak with an expert</Link></div></div>
        </div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-10 sm:py-18 lg:grid-cols-[1fr_1.08fr] lg:items-center lg:px-12 xl:px-16">
        <div className="relative aspect-[1.05/1] overflow-hidden rounded-2xl bg-[#eee8db] shadow-[0_18px_38px_rgba(35,48,37,0.12)] sm:aspect-[1.25/1]"><Image src={storyImage} alt="Rudraksha sourced with care" fill sizes="(max-width: 1024px) 100vw, 44vw" className="object-cover" /><div className="absolute bottom-4 left-4 rounded-xl bg-white/92 px-4 py-3 shadow-sm"><p className="text-[9px] font-extrabold tracking-[0.14em] text-[#966f3e] uppercase">Rooted in Nepal</p><p className="mt-1 text-[13px] font-bold text-[#1f3a2e]">Direct from trusted collectors</p></div></div>
        <div><p className="text-[10px] font-extrabold tracking-[0.2em] text-[#9a7647] uppercase">The beginning</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-[37px] font-bold leading-[0.92] text-[#173b2d] sm:text-[48px]">A journey from the Himalayas</h2><div className="mt-5 space-y-4 text-[13px] leading-relaxed text-[#647067] sm:text-[15px]"><p>Nepali Rudraksha began with a simple mission: make authentic Himalayan Rudraksha accessible to every sincere spiritual seeker.</p><p>We work directly with trusted collectors, inspect every bead, count its Mukhis, and send selected pieces to accredited laboratories for verification.</p><p>For us, this is more than commerce. It is a way to share a living spiritual heritage with respect, care, and complete transparency.</p></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl border border-[#eadfce] bg-[#fffaf1] p-4"><ShieldCheck className="size-5 text-[#98783e]" /><p className="mt-2 text-[12px] font-bold text-[#294237]">Verified sourcing</p><p className="mt-1 text-[10px] leading-snug text-[#737b73]">Every piece is carefully checked.</p></div><div className="rounded-xl border border-[#eadfce] bg-[#fffaf1] p-4"><Sparkles className="size-5 text-[#98783e]" /><p className="mt-2 text-[12px] font-bold text-[#294237]">Vedic care</p><p className="mt-1 text-[10px] leading-snug text-[#737b73]">Handled with reverence and intention.</p></div></div></div>
      </section>

      <section className="border-y border-[#ece4d7] bg-[#f8f4ec]"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-10 sm:py-16 lg:px-12 xl:px-16"><div className="max-w-xl"><p className="text-[10px] font-extrabold tracking-[0.2em] text-[#9a7647] uppercase">What we stand for</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-[37px] font-bold leading-none text-[#173b2d] sm:text-[46px]">Our core values</h2></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{ icon: ShieldCheck, title: 'Authenticity first', desc: 'Every bead is sourced responsibly and verified before it reaches you.' }, { icon: Award, title: 'Quality excellence', desc: 'Only the finest, naturally formed Rudraksha enter our collection.' }, { icon: Heart, title: 'Spiritual devotion', desc: 'We handle every sacred bead with care and traditional respect.' }, { icon: Globe2, title: 'Global reach', desc: 'Himalayan blessings, carefully delivered to seekers worldwide.' }].map((value) => <article key={value.title} className="rounded-2xl border border-[#e6ddcf] bg-white p-5 shadow-[0_8px_20px_rgba(35,48,37,0.04)]"><span className="flex size-10 items-center justify-center rounded-full bg-[#f7edd9] text-[#98783e]"><value.icon size={20} /></span><h3 className="mt-5 font-[family-name:var(--font-display)] text-[22px] font-bold leading-none text-[#1c382b]">{value.title}</h3><p className="mt-3 text-[12px] leading-relaxed text-[#707a71]">{value.desc}</p></article>)}</div></div></section>

      <section className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-10 sm:py-16 lg:grid-cols-[1.08fr_1fr] lg:items-center lg:px-12 xl:px-16"><div className="order-2 lg:order-1"><p className="text-[10px] font-extrabold tracking-[0.2em] text-[#9a7647] uppercase">The Nepali Rudraksha difference</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-[37px] font-bold leading-[0.92] text-[#173b2d] sm:text-[46px]">Guidance you can trust</h2><div className="mt-7 space-y-4">{['Direct source from Nepal', 'IGRMS lab-certified selections', 'Personal expert guidance', 'Traditional Vedic energization', 'Secure, trackable delivery'].map((item) => <div key={item} className="flex items-center gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-[#e6f0e8] text-[#276040]"><Check size={14} strokeWidth={3} /></span><p className="text-[13px] font-bold text-[#425248] sm:text-[14px]">{item}</p></div>)}</div><Link href="/contact" className="mt-8 inline-flex h-11 items-center rounded-full bg-[#173b2d] px-6 text-[12px] font-bold text-white hover:bg-[#28523e]">Get personal guidance</Link></div><div className="order-1 relative aspect-[1.1/1] overflow-hidden rounded-2xl bg-[#153a2b] shadow-[0_18px_38px_rgba(35,48,37,0.16)] lg:order-2"><Image src={heritageImage} alt="Himalayan spiritual heritage" fill sizes="(max-width: 1024px) 100vw, 42vw" className="object-cover" /><div className="absolute inset-0 bg-[#082d21]/30" /><p className="absolute bottom-5 left-5 max-w-48 font-[family-name:var(--font-display)] text-[24px] font-bold leading-[0.95] text-white">Tradition, transparency, and care.</p></div></section>

      <section className="bg-[#12392b] text-white"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-y-8 px-5 py-12 text-center sm:grid-cols-4 sm:px-10 lg:px-12 xl:px-16">{[{ value: '10,000+', label: 'Happy customers' }, { value: '22+', label: 'Rudraksha types' }, { value: '15+', label: 'Years of experience' }, { value: '50+', label: 'Countries served' }].map((stat) => <div key={stat.label}><p className="font-[family-name:var(--font-display)] text-[34px] font-bold leading-none text-[#f0cd89] sm:text-[43px]">{stat.value}</p><p className="mt-2 text-[10px] font-medium text-white/70 sm:text-[12px]">{stat.label}</p></div>)}</div></section>

      <section className="mx-auto max-w-5xl px-5 py-14 text-center sm:px-10 sm:py-16"><p className="text-[10px] font-extrabold tracking-[0.2em] text-[#9a7647] uppercase">Customer love</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-[35px] font-bold leading-none text-[#173b2d] sm:text-[45px]">What seekers say</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{[{ name: 'Aditya Verma', city: 'Pune', quote: 'The lab certification and thoughtful guidance gave me complete confidence in my choice.' }, { name: 'Lakshmi Nair', city: 'Chennai', quote: 'Every bead has been genuine and beautifully prepared. It has become my trusted source.' }].map((review) => <article key={review.name} className="rounded-2xl border border-[#e8dfd1] bg-[#fffaf2] p-6 text-left"><div className="flex gap-1 text-[#b8934d]">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={14} className="fill-current" />)}</div><p className="mt-4 text-[13px] leading-relaxed text-[#606b62]">“{review.quote}”</p><p className="mt-5 text-[12px] font-bold text-[#1d3a2d]">{review.name}</p><p className="text-[10px] text-[#7a827a]">{review.city}</p></article>)}</div><div className="mt-10 rounded-2xl bg-[#f5ecd9] px-6 py-8"><h2 className="font-[family-name:var(--font-display)] text-[30px] font-bold leading-none text-[#173b2d]">Begin your spiritual journey</h2><p className="mx-auto mt-3 max-w-xl text-[12px] leading-relaxed text-[#687268]">Explore our authenticated collection and find the Rudraksha that resonates with your path.</p><Link href="/shop" className="mt-6 inline-flex h-11 items-center rounded-full bg-[#173b2d] px-6 text-[12px] font-bold text-white hover:bg-[#28523e]">Shop Rudraksha</Link></div></section>
    </main>
  );
}
